# Dependencies
markdown:         rdiscount
highlights:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rebecca Holmes
tagline:          ""
url:              http://rebeccaholmes.net
paginate:         5
baseurl:          ""
excerpt_separator: <!--more-->

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/piscisvolans/piscisvolans.github.io
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/rss.xml'

name: Rebecca Holmes' Blog
description: Science, writing, and other stuff.
  