# Dependencies
markdown:         kramdown
highlights:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rebecca Holmes
name:			  Rebecca Holmes' Blog
tagline:          "Rebecca Holmes"
url:              http://rebeccaholmes.net
description:	  Science, writing, and other stuff.
paginate:         5
baseurl:          ""
excerpt_separator: <!--more-->
author:
  name:           Rebecca Holmes
  url:            https://twitter.com/rebeccaholmes
  email:          rebecca.morgan.holmes@gmail.com

# Custom vars
github:
  repo:           https://github.com/piscisvolans/piscisvolans.github.io
pages_list:       
  About: '/about'
  Poetry: '/poetry'
  Archive: '/archive'
  Feed: '/rss.xml'
