# Dependencies
markdown:         kramdown
highlights:       pygments
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Rebecca Holmes Sandoval
name:			  Rebecca Holmes Sandoval's Blog
tagline:          "Rebecca Holmes Sandoval"
url:              http://rebeccaholmes.net
description:	  Science, writing, and other stuff.
paginate:         5
baseurl:          ""
excerpt_separator: <!--more-->
author:
  name:           Rebecca Holmes Sandoval
  url:            https://twitter.com/rebeccaholmes
  email:          rebecca.h.sandoval@gmail.com

# Custom vars
github:
  repo:           https://github.com/piscisvolans/piscisvolans.github.io
pages_list:       
  About: '/about'
  Poetry: '/poetry'
  Archive: '/archive'
  Feed: '/rss.xml'
