# Dependencies
markdown:         rdiscount
highlights:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Rebecca Holmes
tagline:          ""
url:              http://rebeccaholmes.net
paginate:         5
baseurl:          /
author:
  name:           Rebecca Holmes
  url:            https://twitter.com/rebeccaholmes
  email:          rebecca.morgan.holmes@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/piscisvolans/piscisvolans.github.io
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
